[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x0812167eaf85bc404e57df907dad63c663de1ba923e70e86847d539a339c8de8'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]